name: Pompeii
version: 1.0 / 5GEHASFT
author: defcon
main: io.pompeii.main.Pompeii
description: Pompeii is a lightweight staff plugin

commands:
    ss:
      description: Screenshare
    sc:
      description: Chat
    mc:
      description: Mute Chat
    rtp:
      descritpion: Random TP
    rtpxray:
      description: Random TP Xray
    staff:
      description: Staff
    panic:
      description: Panic
    dl:
      description: Death Lookup
    v:
      description: Vanish
    request:
      description: Request
    pompeii:
      description: Developers command